service: backend-produtos

provider:
  name: aws
  runtime: nodejs12.x
  region: sa-east-1
  stage: prod
  memorySize: 128
  timeout: 5
  endpointType: regional
  environment:
    PRODUTOS_TABLE: ${self:service}-${opt:stage, self:provider.stage}

resources:
  Resources:
    NotesTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.PRODUTOS_TABLE}
        AttributeDefinitions:
          - AttributeName: produto_id
            AttributeType: N
          - AttributeName: nome
            AttributeType: S
        KeySchema:
          - AttributeName: produto_id
            KeyType: HASH
          - AttributeName: nome
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1